// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eGreeting.Models;

namespace eGreeting.Migrations
{
    [DbContext(typeof(MariaDBContext))]
    [Migration("20200512100150_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("eGreeting.Models.Card", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime");

                    b.Property<string>("ImageName")
                        .HasColumnType("text");

                    b.Property<byte>("IsActive")
                        .HasColumnType("tinyint");

                    b.HasKey("CardId");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            CardId = 1,
                            CardName = "Birthday-01",
                            CategoryId = 1,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 557, DateTimeKind.Local).AddTicks(9773),
                            ImageName = "b-image1.png",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 2,
                            CardName = "Birthday-02",
                            CategoryId = 1,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(657),
                            ImageName = "b-image2.png",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 3,
                            CardName = "Birthday-03",
                            CategoryId = 1,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(673),
                            ImageName = "b-image3.png",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 4,
                            CardName = "Birthday-04",
                            CategoryId = 1,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(675),
                            ImageName = "b-image4.png",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 5,
                            CardName = "Birthday-05",
                            CategoryId = 1,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(677),
                            ImageName = "b-image5.png",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 6,
                            CardName = "Birthday-06",
                            CategoryId = 1,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(680),
                            ImageName = "b-image6.png",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 7,
                            CardName = "Birthday-07",
                            CategoryId = 1,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(682),
                            ImageName = "b-image7.png",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 8,
                            CardName = "Birthday-08",
                            CategoryId = 1,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(684),
                            ImageName = "b-image8.jpg",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 9,
                            CardName = "Birthday-09",
                            CategoryId = 1,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(686),
                            ImageName = "b-image9.png",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 10,
                            CardName = "Birthday-10",
                            CategoryId = 1,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(688),
                            ImageName = "b-image10.png",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 11,
                            CardName = "Birthday-11",
                            CategoryId = 1,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(690),
                            ImageName = "b-image11.png",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 12,
                            CardName = "Birthday-12",
                            CategoryId = 1,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(692),
                            ImageName = "b-image12.png",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 13,
                            CardName = "Birthday-13",
                            CategoryId = 1,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(694),
                            ImageName = "b-image13.png",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 14,
                            CardName = "Birthday-14",
                            CategoryId = 1,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(696),
                            ImageName = "b-image14.png",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 15,
                            CardName = "Birthday-15",
                            CategoryId = 1,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(698),
                            ImageName = "b-image15.png",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 16,
                            CardName = "Birthday-16",
                            CategoryId = 1,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(700),
                            ImageName = "b-image16.png",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 17,
                            CardName = "Birthday-17",
                            CategoryId = 1,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(701),
                            ImageName = "b-image17.png",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 18,
                            CardName = "Birthday-18",
                            CategoryId = 1,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(704),
                            ImageName = "b-image18.png",
                            IsActive = (byte)0
                        },
                        new
                        {
                            CardId = 54,
                            CardName = "NewYear-01",
                            CategoryId = 2,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(706),
                            ImageName = "n-image1.png",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 19,
                            CardName = "NewYear-02",
                            CategoryId = 2,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(708),
                            ImageName = "n-image2.jpg",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 20,
                            CardName = "NewYear-03",
                            CategoryId = 2,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(710),
                            ImageName = "n-image3.png",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 21,
                            CardName = "NewYear-04",
                            CategoryId = 2,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(711),
                            ImageName = "n-image4.jpg",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 22,
                            CardName = "NewYear-05",
                            CategoryId = 2,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(713),
                            ImageName = "n-image5.jpg",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 23,
                            CardName = "NewYear-06",
                            CategoryId = 2,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(715),
                            ImageName = "n-image6.jpg",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 24,
                            CardName = "NewYear-07",
                            CategoryId = 2,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(717),
                            ImageName = "n-image7.png",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 25,
                            CardName = "NewYear-08",
                            CategoryId = 2,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(719),
                            ImageName = "n-image8.png",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 26,
                            CardName = "NewYear-09",
                            CategoryId = 2,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(721),
                            ImageName = "n-image9.png",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 27,
                            CardName = "NewYear-10",
                            CategoryId = 2,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(723),
                            ImageName = "n-image10.png",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 28,
                            CardName = "NewYear-11",
                            CategoryId = 2,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(724),
                            ImageName = "n-image11.jpg",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 29,
                            CardName = "NewYear-12",
                            CategoryId = 2,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(726),
                            ImageName = "n-image12.jpg",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 30,
                            CardName = "NewYear-13",
                            CategoryId = 2,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(728),
                            ImageName = "n-image13.jpg",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 31,
                            CardName = "NewYear-14",
                            CategoryId = 2,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(730),
                            ImageName = "n-image14.jpg",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 32,
                            CardName = "NewYear-15",
                            CategoryId = 2,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(733),
                            ImageName = "n-image15.jpg",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 33,
                            CardName = "NewYear-16",
                            CategoryId = 2,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(734),
                            ImageName = "n-image16.jpg",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 34,
                            CardName = "NewYear-17",
                            CategoryId = 2,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(736),
                            ImageName = "n-image17.jpg",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 35,
                            CardName = "NewYear-18",
                            CategoryId = 2,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(738),
                            ImageName = "n-image18.jpg",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 36,
                            CardName = "Festival-01",
                            CategoryId = 3,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(740),
                            ImageName = "f-image1.png",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 37,
                            CardName = "Festival-02",
                            CategoryId = 3,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(742),
                            ImageName = "f-image2.jpg",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 38,
                            CardName = "Festival-03",
                            CategoryId = 3,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(744),
                            ImageName = "f-image3.jpg",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 39,
                            CardName = "Festival-04",
                            CategoryId = 3,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(746),
                            ImageName = "f-image4.jpg",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 40,
                            CardName = "Festival-05",
                            CategoryId = 3,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(748),
                            ImageName = "f-image5.jpg",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 41,
                            CardName = "Festival-06",
                            CategoryId = 3,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(749),
                            ImageName = "f-image6.jpg",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 42,
                            CardName = "Festival-07",
                            CategoryId = 3,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(751),
                            ImageName = "f-image7.jpg",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 43,
                            CardName = "Festival-08",
                            CategoryId = 3,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(753),
                            ImageName = "f-image8.png",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 44,
                            CardName = "Festival-09",
                            CategoryId = 3,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(755),
                            ImageName = "f-image9.png",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 45,
                            CardName = "Festival-10",
                            CategoryId = 3,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(757),
                            ImageName = "f-image10.png",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 46,
                            CardName = "Festival-11",
                            CategoryId = 3,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(759),
                            ImageName = "f-image11.png",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 47,
                            CardName = "Festival-12",
                            CategoryId = 3,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(761),
                            ImageName = "f-image12.png",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 48,
                            CardName = "Festival-13",
                            CategoryId = 3,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(763),
                            ImageName = "f-image13.jpg",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 49,
                            CardName = "Festival-14",
                            CategoryId = 3,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(765),
                            ImageName = "f-image14.jpg",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 50,
                            CardName = "Festival-15",
                            CategoryId = 3,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(767),
                            ImageName = "f-image15.png",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 51,
                            CardName = "Festival-16",
                            CategoryId = 3,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(769),
                            ImageName = "f-image16.jpg",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 52,
                            CardName = "Festival-17",
                            CategoryId = 3,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(771),
                            ImageName = "f-image17.png",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CardId = 53,
                            CardName = "Festival-18",
                            CategoryId = 3,
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 558, DateTimeKind.Local).AddTicks(773),
                            ImageName = "f-image18.jpg",
                            IsActive = (byte)1
                        });
                });

            modelBuilder.Entity("eGreeting.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<byte>("IsActive")
                        .HasColumnType("tinyint");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Birthday",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Newyear",
                            IsActive = (byte)1
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Festival",
                            IsActive = (byte)1
                        });
                });

            modelBuilder.Entity("eGreeting.Models.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("varchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime");

                    b.Property<byte>("IsChecked")
                        .HasColumnType("tinyint");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("FeedbackId");

                    b.ToTable("Feedbacks");

                    b.HasData(
                        new
                        {
                            FeedbackId = 1,
                            Content = "Hello Handsome Guys",
                            DateCreated = new DateTime(2020, 5, 12, 17, 1, 49, 555, DateTimeKind.Local).AddTicks(5584),
                            IsChecked = (byte)0,
                            Subject = "user",
                            Username = "user"
                        });
                });

            modelBuilder.Entity("eGreeting.Models.PaymentInfo", b =>
                {
                    b.Property<int>("PayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<long>("BankAccount")
                        .HasColumnType("bigint");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateExpire")
                        .HasColumnType("datetime");

                    b.Property<byte>("IsActive")
                        .HasColumnType("tinyint");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("PayId");

                    b.ToTable("PaymentInfos");

                    b.HasData(
                        new
                        {
                            PayId = 1,
                            BankAccount = 9405123465478545L,
                            BankName = "ACB",
                            DateExpire = new DateTime(2022, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = (byte)0,
                            UserName = "user"
                        });
                });

            modelBuilder.Entity("eGreeting.Models.SubscribeList", b =>
                {
                    b.Property<int>("SubscribeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("SubscribeEmail")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("SubscribeId");

                    b.ToTable("SubscribeLists");
                });

            modelBuilder.Entity("eGreeting.Models.Transaction", b =>
                {
                    b.Property<int>("TransId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("varchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<string>("Receiver")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime>("TimeSend")
                        .HasColumnType("datetime");

                    b.Property<string>("TransImage")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("TransId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            TransId = 1,
                            CardId = 0,
                            Content = "Hello your 30! Wish you see many many lucky with this old, happiness and healthy",
                            Receiver = "receiver@gmail.com",
                            Status = (byte)0,
                            Subject = "Happy Birthday my friend",
                            TimeSend = new DateTime(2020, 5, 12, 17, 1, 49, 557, DateTimeKind.Local).AddTicks(1685),
                            TransImage = "b-image1.png",
                            Username = "user"
                        });
                });

            modelBuilder.Entity("eGreeting.Models.User", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<byte>("Gender")
                        .HasColumnType("tinyint");

                    b.Property<byte>("IsActive")
                        .HasColumnType("tinyint");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint");

                    b.HasKey("UserName");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserName = "admin",
                            Email = "admin@egreeting.com",
                            FullName = "Admin",
                            Gender = (byte)1,
                            IsActive = (byte)1,
                            Password = "admin1234",
                            Phone = "0762327226",
                            Role = (byte)0
                        },
                        new
                        {
                            UserName = "user",
                            Email = "test@gmail.com",
                            FullName = "Test User",
                            Gender = (byte)1,
                            IsActive = (byte)1,
                            Password = "123123123",
                            Phone = "0762371254",
                            Role = (byte)1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
