// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eGreeting.Models;

namespace eGreeting.Migrations
{
    [DbContext(typeof(MariaDBContext))]
    partial class MariaDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("eGreeting.Models.Card", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime");

                    b.Property<string>("ImageName")
                        .HasColumnType("text");

                    b.Property<string>("NameCard")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("CardId");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            CardId = 1,
                            Category = "Birthday",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(5998),
                            ImageName = "b-image1.png",
                            NameCard = "Birthday-01"
                        },
                        new
                        {
                            CardId = 2,
                            Category = "Birthday",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(6921),
                            ImageName = "b-image2.png",
                            NameCard = "Birthday-02"
                        },
                        new
                        {
                            CardId = 3,
                            Category = "Birthday",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(6956),
                            ImageName = "b-image3.png",
                            NameCard = "Birthday-03"
                        },
                        new
                        {
                            CardId = 4,
                            Category = "Birthday",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(6958),
                            ImageName = "b-image4.png",
                            NameCard = "Birthday-04"
                        },
                        new
                        {
                            CardId = 5,
                            Category = "Birthday",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(6960),
                            ImageName = "b-image5.png",
                            NameCard = "Birthday-05"
                        },
                        new
                        {
                            CardId = 6,
                            Category = "Birthday",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(6962),
                            ImageName = "b-image6.png",
                            NameCard = "Birthday-06"
                        },
                        new
                        {
                            CardId = 7,
                            Category = "Birthday",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(6964),
                            ImageName = "b-image7.png",
                            NameCard = "Birthday-07"
                        },
                        new
                        {
                            CardId = 8,
                            Category = "Birthday",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(6966),
                            ImageName = "b-image8.jpg",
                            NameCard = "Birthday-08"
                        },
                        new
                        {
                            CardId = 9,
                            Category = "Birthday",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(6968),
                            ImageName = "b-image9.png",
                            NameCard = "Birthday-09"
                        },
                        new
                        {
                            CardId = 10,
                            Category = "Birthday",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(6970),
                            ImageName = "b-image10.png",
                            NameCard = "Birthday-10"
                        },
                        new
                        {
                            CardId = 11,
                            Category = "Birthday",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(6972),
                            ImageName = "b-image11.png",
                            NameCard = "Birthday-11"
                        },
                        new
                        {
                            CardId = 12,
                            Category = "Birthday",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(6973),
                            ImageName = "b-image12.png",
                            NameCard = "Birthday-12"
                        },
                        new
                        {
                            CardId = 13,
                            Category = "Birthday",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(6975),
                            ImageName = "b-image13.png",
                            NameCard = "Birthday-13"
                        },
                        new
                        {
                            CardId = 14,
                            Category = "Birthday",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(6977),
                            ImageName = "b-image14.png",
                            NameCard = "Birthday-14"
                        },
                        new
                        {
                            CardId = 15,
                            Category = "Birthday",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(6980),
                            ImageName = "b-image15.png",
                            NameCard = "Birthday-15"
                        },
                        new
                        {
                            CardId = 16,
                            Category = "Birthday",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(6982),
                            ImageName = "b-image16.png",
                            NameCard = "Birthday-16"
                        },
                        new
                        {
                            CardId = 17,
                            Category = "Birthday",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(6983),
                            ImageName = "b-image17.png",
                            NameCard = "Birthday-17"
                        },
                        new
                        {
                            CardId = 18,
                            Category = "Birthday",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(6985),
                            ImageName = "b-image18.png",
                            NameCard = "Birthday-18"
                        },
                        new
                        {
                            CardId = 54,
                            Category = "NewYear",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(6987),
                            ImageName = "n-image1.png",
                            NameCard = "NewYear-01"
                        },
                        new
                        {
                            CardId = 19,
                            Category = "NewYear",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(6989),
                            ImageName = "n-image2.jpg",
                            NameCard = "NewYear-02"
                        },
                        new
                        {
                            CardId = 20,
                            Category = "NewYear",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(6990),
                            ImageName = "n-image3.png",
                            NameCard = "NewYear-03"
                        },
                        new
                        {
                            CardId = 21,
                            Category = "NewYear",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(6993),
                            ImageName = "n-image4.jpg",
                            NameCard = "NewYear-04"
                        },
                        new
                        {
                            CardId = 22,
                            Category = "NewYear",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(6994),
                            ImageName = "n-image5.jpg",
                            NameCard = "NewYear-05"
                        },
                        new
                        {
                            CardId = 23,
                            Category = "NewYear",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(6996),
                            ImageName = "n-image6.jpg",
                            NameCard = "NewYear-06"
                        },
                        new
                        {
                            CardId = 24,
                            Category = "NewYear",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(6998),
                            ImageName = "n-image7.png",
                            NameCard = "NewYear-07"
                        },
                        new
                        {
                            CardId = 25,
                            Category = "NewYear",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(7000),
                            ImageName = "n-image8.png",
                            NameCard = "NewYear-08"
                        },
                        new
                        {
                            CardId = 26,
                            Category = "NewYear",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(7003),
                            ImageName = "n-image9.png",
                            NameCard = "NewYear-09"
                        },
                        new
                        {
                            CardId = 27,
                            Category = "NewYear",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(7005),
                            ImageName = "n-image10.png",
                            NameCard = "NewYear-10"
                        },
                        new
                        {
                            CardId = 28,
                            Category = "NewYear",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(7007),
                            ImageName = "n-image11.jpg",
                            NameCard = "NewYear-11"
                        },
                        new
                        {
                            CardId = 29,
                            Category = "NewYear",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(7009),
                            ImageName = "n-image12.jpg",
                            NameCard = "NewYear-12"
                        },
                        new
                        {
                            CardId = 30,
                            Category = "NewYear",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(7010),
                            ImageName = "n-image13.jpg",
                            NameCard = "NewYear-13"
                        },
                        new
                        {
                            CardId = 31,
                            Category = "NewYear",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(7013),
                            ImageName = "n-image14.jpg",
                            NameCard = "NewYear-14"
                        },
                        new
                        {
                            CardId = 32,
                            Category = "NewYear",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(7014),
                            ImageName = "n-image15.jpg",
                            NameCard = "NewYear-15"
                        },
                        new
                        {
                            CardId = 33,
                            Category = "NewYear",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(7016),
                            ImageName = "n-image16.jpg",
                            NameCard = "NewYear-16"
                        },
                        new
                        {
                            CardId = 34,
                            Category = "NewYear",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(7018),
                            ImageName = "n-image17.jpg",
                            NameCard = "NewYear-17"
                        },
                        new
                        {
                            CardId = 35,
                            Category = "NewYear",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(7020),
                            ImageName = "n-image18.jpg",
                            NameCard = "NewYear-18"
                        },
                        new
                        {
                            CardId = 36,
                            Category = "Festival",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(7023),
                            ImageName = "f-image1.png",
                            NameCard = "Festival-01"
                        },
                        new
                        {
                            CardId = 37,
                            Category = "Festival",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(7025),
                            ImageName = "f-image2.jpg",
                            NameCard = "Festival-02"
                        },
                        new
                        {
                            CardId = 38,
                            Category = "Festival",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(7027),
                            ImageName = "f-image3.jpg",
                            NameCard = "Festival-03"
                        },
                        new
                        {
                            CardId = 39,
                            Category = "Festival",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(7028),
                            ImageName = "f-image4.jpg",
                            NameCard = "Festival-04"
                        },
                        new
                        {
                            CardId = 40,
                            Category = "Festival",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(7030),
                            ImageName = "f-image5.jpg",
                            NameCard = "Festival-05"
                        },
                        new
                        {
                            CardId = 41,
                            Category = "Festival",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(7032),
                            ImageName = "f-image6.jpg",
                            NameCard = "Festival-06"
                        },
                        new
                        {
                            CardId = 42,
                            Category = "Festival",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(7034),
                            ImageName = "f-image7.jpg",
                            NameCard = "Festival-07"
                        },
                        new
                        {
                            CardId = 43,
                            Category = "Festival",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(7036),
                            ImageName = "f-image8.png",
                            NameCard = "Festival-08"
                        },
                        new
                        {
                            CardId = 44,
                            Category = "Festival",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(7038),
                            ImageName = "f-image9.png",
                            NameCard = "Festival-09"
                        },
                        new
                        {
                            CardId = 45,
                            Category = "Festival",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(7040),
                            ImageName = "f-image10.png",
                            NameCard = "Festival-10"
                        },
                        new
                        {
                            CardId = 46,
                            Category = "Festival",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(7042),
                            ImageName = "f-image11.png",
                            NameCard = "Festival-11"
                        },
                        new
                        {
                            CardId = 47,
                            Category = "Festival",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(7043),
                            ImageName = "f-image12.png",
                            NameCard = "Festival-12"
                        },
                        new
                        {
                            CardId = 48,
                            Category = "Festival",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(7045),
                            ImageName = "f-image13.jpg",
                            NameCard = "Festival-13"
                        },
                        new
                        {
                            CardId = 49,
                            Category = "Festival",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(7047),
                            ImageName = "f-image14.jpg",
                            NameCard = "Festival-14"
                        },
                        new
                        {
                            CardId = 50,
                            Category = "Festival",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(7048),
                            ImageName = "f-image15.png",
                            NameCard = "Festival-15"
                        },
                        new
                        {
                            CardId = 51,
                            Category = "Festival",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(7050),
                            ImageName = "f-image16.jpg",
                            NameCard = "Festival-16"
                        },
                        new
                        {
                            CardId = 52,
                            Category = "Festival",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(7052),
                            ImageName = "f-image17.png",
                            NameCard = "Festival-17"
                        },
                        new
                        {
                            CardId = 53,
                            Category = "Festival",
                            DateCreated = new DateTime(2020, 5, 7, 16, 44, 39, 943, DateTimeKind.Local).AddTicks(7054),
                            ImageName = "f-image18.jpg",
                            NameCard = "Festival-18"
                        });
                });

            modelBuilder.Entity("eGreeting.Models.EmailList", b =>
                {
                    b.Property<int>("EmailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ListEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EmailId");

                    b.ToTable("EmailLists");
                });

            modelBuilder.Entity("eGreeting.Models.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("varchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<DateTime>("DataCreated")
                        .HasColumnType("datetime");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("FeedbackId");

                    b.ToTable("Feedbacks");

                    b.HasData(
                        new
                        {
                            FeedbackId = 1,
                            Content = "Hello Handsome Guys",
                            DataCreated = new DateTime(2020, 5, 7, 16, 44, 39, 940, DateTimeKind.Local).AddTicks(7443),
                            Subject = "test",
                            Username = "test"
                        });
                });

            modelBuilder.Entity("eGreeting.Models.PaymentInfo", b =>
                {
                    b.Property<int>("PayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<long>("BankAccount")
                        .HasColumnType("bigint");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateExpire")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("PayId");

                    b.ToTable("PaymentInfos");

                    b.HasData(
                        new
                        {
                            PayId = 1,
                            BankAccount = 9405123465478545L,
                            BankName = "ACB",
                            DateExpire = new DateTime(2022, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            UserId = 2,
                            UserName = "test"
                        });
                });

            modelBuilder.Entity("eGreeting.Models.Transaction", b =>
                {
                    b.Property<int>("TransId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("varchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<string>("ImageNameTrans")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("NameCard")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Receiver")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime>("TimeSend")
                        .HasColumnType("datetime");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("TransId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            TransId = 1,
                            Content = "Hello your 30! Wish you see many many lucky with this old, happiness and healthy",
                            ImageNameTrans = "b-image1.png",
                            NameCard = "Birthday-01",
                            Receiver = "receiver@gmail.com",
                            Subject = "Happy Birthday my friend",
                            TimeSend = new DateTime(2020, 5, 7, 16, 44, 39, 942, DateTimeKind.Local).AddTicks(539),
                            Username = "test"
                        });
                });

            modelBuilder.Entity("eGreeting.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeactive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSubcribeReceive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSubcribeSend")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVIP")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RePassword")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("Role")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "admin@egreeting.com",
                            FullName = "Admin",
                            Gender = true,
                            IsDeactive = false,
                            IsSubcribeReceive = false,
                            IsSubcribeSend = false,
                            IsVIP = true,
                            Password = "admin1234",
                            Phone = "0762327226",
                            RePassword = "admin1234",
                            Role = true,
                            UserName = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "test@gmail.com",
                            FullName = "test",
                            Gender = true,
                            IsDeactive = false,
                            IsSubcribeReceive = false,
                            IsSubcribeSend = false,
                            IsVIP = false,
                            Password = "123123123",
                            Phone = "0762371254",
                            RePassword = "123123123",
                            Role = false,
                            UserName = "test"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
